const seedSchedule={version:1,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/London',events:[]};
const dayAliases={sunday:'sun',monday:'mon',tuesday:'tue',wednesday:'wed',thursday:'thu',friday:'fri',saturday:'sat',sun:'sun',mon:'mon',tue:'tue',wed:'wed',thu:'thu',fri:'fri',sat:'sat',daily:'daily',everyday:'daily',every:'daily',all:'daily'};
function normalizeDays(raw){const list=Array.isArray(raw)?raw:String(raw==null?'':raw).split(',');const out=[];for(const entry of list){const token=String(entry).trim().toLowerCase();if(!token)continue;const mapped=dayAliases[token];if(!mapped)return null;if(!out.includes(mapped))out.push(mapped)}return out.length?out:null}
function validateEventShape(item){if(!item||typeof item!=='object')return null;if(typeof item.id!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(item.id))return null;if(typeof item.time!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(item.time))return null;if(typeof item.label!=='string'||!item.label.trim()||item.label.length>200)return null;if(!Array.isArray(item.medicines)||!item.medicines.length||item.medicines.length>32)return null;if(item.medicines.some(m=>typeof m!=='string'||!m.trim()||m.length>500))return null;const days=normalizeDays(item.days);if(!days)return null;return{id:item.id,enabled:Boolean(item.enabled),time:item.time,label:item.label.trim(),medicines:item.medicines.map(m=>m.trim()),instructions:typeof item.instructions==='string'?item.instructions.slice(0,2000):'',days,start_date:typeof item.start_date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(item.start_date)?item.start_date:null,end_date:typeof item.end_date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(item.end_date)?item.end_date:null}}
function validateScheduleShape(value){if(!value||typeof value!=='object'||typeof value.timezone!=='string'||value.timezone.length>100||!Array.isArray(value.events)||value.events.length>64)return null;const events=[];for(const item of value.events){const normalized=validateEventShape(item);if(!normalized)return null;events.push(normalized)}return{version:1,timezone:value.timezone,events}}
const key='medication-reminder-schedule-v1',settingsKey='medication-reminder-settings-v1',unpairedKey='medication-reminder-mobile-unpaired-v1';const readStoredJson=(storageKey,fallback)=>{try{const raw=localStorage.getItem(storageKey);return raw===null?fallback:JSON.parse(raw)}catch(error){console.warn(`Ignoring invalid local data for ${storageKey}`,error);return fallback}};const emptySchedule=timezone=>({version:1,timezone:timezone||Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/London',events:[]});const storedSchedule=readStoredJson(key,null);let explicitlyUnpaired=false;try{explicitlyUnpaired=localStorage.getItem(unpairedKey)==='1'}catch(error){console.warn('Could not read the mobile unpair state',error)}let scheduleLoadWarning='';const safeStoredTimezone=storedSchedule&&typeof storedSchedule.timezone==='string'?storedSchedule.timezone:undefined;let schedule;if(explicitlyUnpaired){schedule=emptySchedule(safeStoredTimezone)}else if(storedSchedule===null){schedule=structuredClone(seedSchedule)}else{const validatedSchedule=validateScheduleShape(storedSchedule);if(validatedSchedule){schedule=validatedSchedule}else{schedule=emptySchedule(safeStoredTimezone);scheduleLoadWarning='Your saved schedule could not be read and was reset to empty. Please re-add your reminders.'}}if(explicitlyUnpaired){try{localStorage.setItem(key,JSON.stringify(schedule))}catch(error){console.warn('Could not persist the cleared mobile schedule',error)}}let settings=readStoredJson(settingsKey,null)||{volume:70,sound:'chime'};if(!['chime','bright','warm','urgent','quiet'].includes(settings.sound))settings.sound='chime';let deferredPrompt=null;
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const save=()=>{try{localStorage.setItem(key,JSON.stringify(schedule));if(!window.__medicationSyncApplying)window.dispatchEvent(new CustomEvent('medication-schedule-changed'));return true}catch(error){console.error('Schedule storage failed',error);alert('The schedule could not be saved on this device. Check browser storage permissions and available space.');return false}};const timeNow=()=>new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
const takenKey='medication-reminder-taken-v1';let taken=readStoredJson(takenKey,{});if(!taken||Array.isArray(taken)||typeof taken!=='object')taken={};
const localDateKey=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
function active(e,d=new Date()){if(!e.enabled)return false;const day=['sun','mon','tue','wed','thu','fri','sat'][d.getDay()];if(!e.days.includes('daily')&&!e.days.includes(day))return false;const iso=localDateKey(d);return(!e.start_date||iso>=e.start_date)&&(!e.end_date||iso<=e.end_date)}
function renderSchedules(){const list=[...schedule.events].sort((a,b)=>a.time.localeCompare(b.time));$('#scheduleList').innerHTML=list.length?list.map(e=>`<article class="schedule-card"><div class="schedule-top"><div><div class="schedule-time">${esc(e.time)}</div><div class="card-title">${esc(e.label)}</div><div class="card-detail">${e.enabled?'Enabled':'Disabled'} · ${esc(e.days.join(', '))}</div></div><div class="schedule-actions"><button class="small-button" data-edit="${esc(e.id)}">Edit</button><button class="small-button danger" data-remove="${esc(e.id)}">Remove</button></div></div><div class="medicine-chips">${e.medicines.map(m=>`<span class="chip">${esc(m)}</span>`).join('')}</div></article>`).join(''):'<div class="empty">No schedules yet. Add your first reminder.</div>'}
function openEditor(id=null){const e=id?schedule.events.find(x=>x.id===id):{id:'',enabled:true,time:'08:00',label:'',medicines:[''],instructions:'',days:['daily'],start_date:'',end_date:''};$('#dialogTitle').textContent=id?'Edit schedule':'Add schedule';$('#eventId').value=e.id;$('#eventTime').value=e.time;$('#eventLabel').value=e.label;$('#eventInstructions').value=e.instructions||'';$('#eventDays').value=e.days.join(',');$('#eventStart').value=e.start_date||'';$('#eventEnd').value=e.end_date||'';$('#eventEnabled').checked=e.enabled;renderMedicineInputs(e.medicines);$('#scheduleDialog').showModal()}
function renderMedicineInputs(items){$('#medicineList').innerHTML='';items.forEach(addMedicineInput)}function addMedicineInput(value=''){const row=document.createElement('div');row.className='medicine-row';row.innerHTML=`<input required maxlength="500" value="${esc(value)}" placeholder="Medication or item"><button type="button" class="small-button danger" aria-label="Remove medication">×</button>`;row.querySelector('button').onclick=()=>row.remove();$('#medicineList').append(row)}
function saveEditor(){const id=$('#eventId').value||`reminder_${Date.now()}`;const medicines=[...document.querySelectorAll('#medicineList input')].map(x=>x.value.trim()).filter(Boolean);if(!medicines.length){alert('Add at least one medication or item.');return false}if(medicines.length>32){alert('A reminder can include at most 32 medications or items.');return false}const time=$('#eventTime').value,label=$('#eventLabel').value.trim();if(!time||!label){alert('Time, label, and days are required.');return false}const days=normalizeDays($('#eventDays').value);if(!days){alert('Enter valid days: use “daily”, or a comma-separated list of day names such as mon,tue,wed (Monday, Tuesday…).');return false}const e=validateEventShape({id,enabled:$('#eventEnabled').checked,time,label,medicines,instructions:$('#eventInstructions').value,days,start_date:$('#eventStart').value||null,end_date:$('#eventEnd').value||null});if(!e){alert('This reminder could not be saved. Check the time, label, days, and medication fields.');return false}const index=schedule.events.findIndex(x=>x.id===id);if(index<0&&schedule.events.length>=64){alert('You can keep at most 64 reminders. Remove one before adding another.');return false}const previous=[...schedule.events];if(index>=0)schedule.events[index]=e;else schedule.events.push(e);if(!save()){schedule.events=previous;return false}$('#scheduleDialog').close();renderAll();return true}
function playSound(){const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext){alert('Sound preview is not supported by this browser.');return}const ctx=new AudioContext(),gainScale=(settings.volume/100)*.16,patterns={chime:[[523,.0,.28],[659,.18,.34],[784,.36,.48]],bright:[[784,.0,.18],[988,.16,.18],[1175,.32,.34]],warm:[[330,.0,.24],[392,.2,.24],[494,.4,.42]],urgent:[[880,.0,.16],[440,.2,.16],[880,.42,.24]],quiet:[[660,.0,.28]]},notes=patterns[settings.sound]||patterns.chime;notes.forEach(([frequency,start,duration])=>{const o=ctx.createOscillator(),g=ctx.createGain(),when=ctx.currentTime+start;o.type=settings.sound==='warm'?'triangle':'sine';o.frequency.value=frequency;g.gain.setValueAtTime(0,when);g.gain.linearRampToValueAtTime(gainScale,when+.025);g.gain.exponentialRampToValueAtTime(.001,when+duration);o.connect(g);g.connect(ctx.destination);o.start(when);o.stop(when+duration+.03)});setTimeout(()=>ctx.close(),900)}
function renderAll(){renderToday();renderSchedules();$('#timezoneInput').value=schedule.timezone;$('#volumeInput').value=settings.volume;$('#volumeOutput').value=`${settings.volume}%`;$('#soundInput').value=settings.sound}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}View`).classList.add('active')});$('#addSchedule').onclick=()=>openEditor();$('#addMedicine').onclick=()=>addMedicineInput();$('#saveSchedule').onclick=async e=>{e.preventDefault();if(saveEditor())await syncPushSubscription()};$('#volumeInput').oninput=e=>$('#volumeOutput').value=`${e.target.value}%`;$('#testSound').onclick=()=>{settings={...settings,volume:Number($('#volumeInput').value),sound:$('#soundInput').value};playSound()};$('#saveSettings').onclick=()=>{settings={volume:Number($('#volumeInput').value),sound:$('#soundInput').value};schedule.timezone=$('#timezoneInput').value.trim()||'Europe/London';localStorage.setItem(settingsKey,JSON.stringify(settings));save();alert('Settings saved on this device.')};$('#scheduleList').onclick=e=>{const edit=e.target.closest('[data-edit]'),remove=e.target.closest('[data-remove]');if(edit)openEditor(edit.dataset.edit);if(remove&&confirm('Remove this schedule?')){schedule.events=schedule.events.filter(x=>x.id!==remove.dataset.remove);save();renderAll()}};$('#installButton').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installButton').hidden=false});renderAll();if(scheduleLoadWarning)alert(scheduleLoadWarning);setInterval(renderToday,30000);
function updateNotificationStatus(){const status=$('#notificationStatus');const button=$('#enableNotifications');if(!('Notification'in window)){status.textContent='Not supported by this browser';button.disabled=true;return}status.textContent=Notification.permission==='granted'?'Enabled for this device':Notification.permission==='denied'?'Blocked in browser settings':'Not enabled';button.textContent=Notification.permission==='granted'?'Notifications enabled':'Enable notifications'}
async function showBrowserNotification(title,options={}){if('serviceWorker'in navigator){const registration=await navigator.serviceWorker.getRegistration();if(registration)await registration.showNotification(title,options);return}if('Notification'in window)new Notification(title,options)}
async function enableNotifications(){if(!('Notification'in window)){return}const permission=await Notification.requestPermission();updateNotificationStatus();if(permission==='granted')await showBrowserNotification('Medication Reminder',{body:'Local browser notifications are enabled on this device.',tag:'medication-notifications-enabled'})}
let notifiedKeys=new Set(Array.isArray(readStoredJson('medication-reminder-notified-v1',[]))?readStoredJson('medication-reminder-notified-v1',[]):[]);
async function checkForegroundNotifications(){if(!('Notification'in window)||Notification.permission!=='granted')return;const now=new Date(),today=localDateKey(now),current=now.toTimeString().slice(0,5);for(const e of schedule.events.filter(e=>e.enabled&&active(e,now)&&e.time===current)){const key=`${today}|${e.id}|${e.time}`;if(notifiedKeys.has(key))continue;notifiedKeys.add(key);localStorage.setItem('medication-reminder-notified-v1',JSON.stringify([...notifiedKeys].slice(-100)));try{await showBrowserNotification(`Medication due: ${e.label}`,{body:e.medicines.join(' · '),tag:key})}catch(error){console.warn('Foreground notification unavailable',error)}}}
$('#enableNotifications').onclick=enableNotifications;updateNotificationStatus();setInterval(checkForegroundNotifications,30000);
const pushApi='/api';
function nextPushReminders(){const out=[],now=new Date();for(let day=0;day<8;day++){const d=new Date(now);d.setHours(12,0,0,0);d.setDate(d.getDate()+day);schedule.events.filter(e=>active(e,d)).forEach(e=>{const due=new Date(`${localDateKey(d)}T${e.time}:00`);if(due>now)out.push({dueAt:due.getTime(),title:'Medication reminder due',body:'Open Medication Reminder to view the scheduled medicines.',tag:`medication-${due.getTime()}`})})}return out.sort((a,b)=>a.dueAt-b.dueAt).slice(0,32)}
async function syncPushSubscription(){if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window)||Notification.permission!=='granted')return;try{const registration=await navigator.serviceWorker.ready;const publicKey=(await (await fetch(`${pushApi}/vapid-public-key`,{credentials:'same-origin',cache:'no-store'})).json()).publicKey;let subscription=await registration.pushManager.getSubscription();if(!subscription){const base64=publicKey.replace(/-/g,'+').replace(/_/g,'/');subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:Uint8Array.from(atob(base64+'='.repeat((4-base64.length%4)%4)),c=>c.charCodeAt(0))})}const json=subscription.toJSON();await fetch(`${pushApi}/subscriptions`,{method:'POST',headers:{'content-type':'application/json','X-Medication-CSRF':'1'},credentials:'same-origin',cache:'no-store',body:JSON.stringify({...json,timezone:schedule.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone,reminders:nextPushReminders()})})}catch(error){console.warn('Push setup unavailable',error)}}
const priorNotificationHandler=$('#enableNotifications').onclick;$('#enableNotifications').onclick=async()=>{await priorNotificationHandler();if('Notification'in window&&Notification.permission==='granted')await syncPushSubscription()};if('Notification'in window&&Notification.permission==='granted')syncPushSubscription();
function clearPrematureTaken(now=new Date()){const day=localDateKey(now),current=now.toTimeString().slice(0,5);let changed=false;for(const event of schedule.events){const key=`${day}|${event.id}`;if(taken[key]&&event.time>current){delete taken[key];changed=true}}if(changed)localStorage.setItem(takenKey,JSON.stringify(taken))}
function reminderState(e,now){const day=localDateKey(now),key=`${day}|${e.id}`;if(taken[key])return 'Taken';const current=now.toTimeString().slice(0,5);return e.time===current?'Due':e.time<current?'Missed':'Upcoming'}
const dueModalView=window.createMedicationDueModal({dialog:$('#dueDialog'),title:$('#dueTitle'),time:$('#dueTime'),list:$('#dueMedications'),instructions:$('#dueInstructions')});
const dueModalShownKey='medication-reminder-due-modal-shown-v1';let dueModalShown=new Set(Array.isArray(readStoredJson(dueModalShownKey,[]))?readStoredJson(dueModalShownKey,[]):[]),dueQueue=[],currentDue=null;
function persistTaken(){const today=localDateKey(new Date()),entries=Object.entries(taken).filter(([key])=>key>=today);taken=Object.fromEntries(entries.slice(-200));localStorage.setItem(takenKey,JSON.stringify(taken))}
function markOccurrenceTaken(key){taken[key]=Date.now();persistTaken();renderToday()}
function showNextDueModal(){if($('#dueDialog').open||!dueQueue.length)return;currentDue=dueQueue.shift();dueModalView.show(currentDue.event)}
function enqueueDue(event,dueDate){const key=`${localDateKey(dueDate)}|${event.id}`;if(taken[key]||dueModalShown.has(key)||dueQueue.some(item=>item.key===key)||currentDue?.key===key)return;dueModalShown.add(key);localStorage.setItem(dueModalShownKey,JSON.stringify([...dueModalShown].slice(-200)));dueQueue.push({event,key});showNextDueModal()}
function closeDueModal(){dueModalView.close()}
function checkDueModals(targetDate=new Date(),force=false){const targetTime=targetDate.toTimeString().slice(0,5);for(const event of schedule.events.filter(event=>active(event,targetDate)&&event.time===targetTime)){if(force||reminderState(event,targetDate)==='Due')enqueueDue(event,targetDate)}}
$('#dueDialog').addEventListener('close',()=>{currentDue=null;setTimeout(showNextDueModal,0)});
$('#acknowledgeDue').onclick=closeDueModal;$('#markDueTaken').onclick=()=>{if(currentDue)markOccurrenceTaken(currentDue.key);closeDueModal()};
function renderToday(){const d=new Date();clearPrematureTaken(d);$('#todayDate').textContent=d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'});const items=schedule.events.filter(e=>active(e,d)).sort((a,b)=>a.time.localeCompare(b.time));$('#todayList').innerHTML=items.length?items.map(e=>{const state=reminderState(e,d),day=localDateKey(d),key=`${day}|${e.id}`,action=state==='Upcoming'?`<button class="small-button" disabled title="Available when this reminder is due">Mark taken</button>`:state==='Taken'?`<button class="small-button" data-undo-taken="${esc(key)}">Undo taken</button>`:`<button class="small-button" data-taken="${esc(key)}" data-event="${esc(e.id)}">Mark taken</button>`;return `<article class="reminder-card ${state==='Due'?'is-due':''}"><div class="reminder-time">${esc(e.time)}</div><div><div class="card-title">${esc(e.label)}</div><ul class="card-medication-list">${e.medicines.map(item=>`<li>${esc(item)}</li>`).join('')}</ul></div><span class="status-badge">${state}</span>${action}</article>`}).join(''):'<div class="empty">No active reminders today.</div>'}
$('#todayList').addEventListener('click',event=>{const mark=event.target.closest('[data-taken]'),undo=event.target.closest('[data-undo-taken]');if(!mark&&!undo)return;if(undo){delete taken[undo.dataset.undoTaken];persistTaken();renderToday();return}const now=new Date(),item=schedule.events.find(entry=>entry.id===mark.dataset.event);if(!item||item.time>now.toTimeString().slice(0,5))return;markOccurrenceTaken(mark.dataset.taken)});renderToday();checkDueModals();setInterval(checkDueModals,30000);
const dueAtParam=Number(new URLSearchParams(location.search).get('dueAt'));if(Number.isFinite(dueAtParam)&&dueAtParam>0){const dueDate=new Date(dueAtParam);checkDueModals(dueDate,true);const cleanParams=new URLSearchParams(location.search);cleanParams.delete('dueAt');history.replaceState(null,'',`${location.pathname}${cleanParams.size?`?${cleanParams}`:''}${location.hash}`)}
const priorSaveSettings=$('#saveSettings').onclick;$('#saveSettings').onclick=async()=>{await priorSaveSettings();await syncPushSubscription()};
window.getMedicationSchedule=()=>structuredClone(schedule);
window.applySyncedSchedule=incoming=>{if(!validateScheduleShape(incoming)){console.error('Rejected an invalid synced schedule shape');alert('The paired schedule could not be read and was not applied. Your existing schedule was kept.');throw new Error('Invalid synced schedule shape')}const candidate=structuredClone(incoming),serialized=JSON.stringify(candidate);try{localStorage.setItem(key,serialized)}catch(error){console.error('Synced schedule storage failed',error);alert('The paired schedule could not be saved on this device. Your existing schedule was kept.');throw new Error('Local schedule storage failed')}window.__medicationSyncApplying=true;try{schedule=candidate;try{localStorage.removeItem(unpairedKey)}catch(error){console.warn('Could not clear the prior unpaired marker',error)}try{renderAll()}catch(error){console.error('Synced schedule rendering failed',error)}void syncPushSubscription()}finally{window.__medicationSyncApplying=false}};
window.clearMedicationSchedule=()=>{window.__medicationSyncApplying=true;let persisted=true;try{schedule=emptySchedule(schedule.timezone);try{localStorage.setItem(unpairedKey,'1');localStorage.setItem(key,JSON.stringify(schedule));localStorage.removeItem(takenKey);localStorage.removeItem('medication-reminder-notified-v1');localStorage.removeItem(dueModalShownKey)}catch(error){persisted=false;console.error('Could not persist the unpaired mobile state',error)}taken={};notifiedKeys=new Set();dueModalShown=new Set();dueQueue=[];currentDue=null;dueModalView.close();renderAll();void syncPushSubscription();return persisted}finally{window.__medicationSyncApplying=false}};
window.getMedicationPushEndpoint=async()=>{if(!('serviceWorker'in navigator)||!('Notification'in window)||Notification.permission!=='granted')return null;const registration=await navigator.serviceWorker.ready;return(await registration.pushManager.getSubscription())?.endpoint||null};
// The push server can only fire client-precomputed reminder epochs (~32 over ~10 days) and
// cannot regenerate them from the E2E-encrypted schedule, so reminders silently stop ~10 days
// after the app is last opened. Refresh the reminder window on every open/visibility regain and
// once a day so the precomputed horizon is continually pushed forward.
window.addEventListener('focus',()=>void syncPushSubscription());
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')void syncPushSubscription()});
setInterval(()=>{if(document.visibilityState==='visible')void syncPushSubscription()},86400000);
