const seedSchedule={timezone:'Europe/London',events:[{id:'morning_transplant',enabled:true,time:'07:00',label:'Morning transplant medicines',medicines:['Envarsus 12 mg','Mycophenolate mofetil 500 mg','Cefalexin 500 mg (temporary course)'],instructions:'Take Envarsus on an empty stomach. Wait at least 1 hour before breakfast or ActaGain.',days:['daily'],start_date:null,end_date:null},{id:'breakfast_medicines',enabled:true,time:'08:00',label:'Breakfast medicines',medicines:['Aspirin 75 mg','Sitagliptin 100 mg','Dapagliflozin 10 mg','Colecalciferol 20,000 units (Tuesday only)'],instructions:'Take with breakfast. Do not take dapagliflozin during significant illness, dehydration, vomiting or poor intake.',days:['daily'],start_date:null,end_date:null},{id:'actagain_morning',enabled:true,time:'10:00',label:'ActaGain morning nutrition',medicines:['ActaGain 1.5 - bottle 1'],instructions:'Sip slowly over 45-60 minutes. Do not drink it in one go.',days:['daily'],start_date:null,end_date:null},{id:'cefalexin_midday',enabled:true,time:'13:00',label:'Midday antibiotic',medicines:['Cefalexin 500 mg (temporary course)'],instructions:'Disable this reminder when the prescribed antibiotic course is complete.',days:['daily'],start_date:null,end_date:null},{id:'evening_medicines',enabled:true,time:'19:00',label:'Evening medicines',medicines:['Mycophenolate mofetil 500 mg','Cefalexin 500 mg (temporary course)','Atorvastatin 20 mg'],instructions:'Take the evening mycophenolate about 12 hours after the morning dose.',days:['daily'],start_date:null,end_date:null},{id:'actagain_evening',enabled:true,time:'20:00',label:'ActaGain evening nutrition',medicines:['ActaGain 1.5 - bottle 2'],instructions:'Sip slowly over 45-60 minutes after dinner.',days:['daily'],start_date:null,end_date:null}]};
const key='medication-reminder-schedule-v1',settingsKey='medication-reminder-settings-v1';let schedule=JSON.parse(localStorage.getItem(key)||'null')||structuredClone(seedSchedule);let settings=JSON.parse(localStorage.getItem(settingsKey)||'null')||{volume:70,sound:'chime'};if(!['chime','bright','warm','urgent','quiet'].includes(settings.sound))settings.sound='chime';let deferredPrompt=null;
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const save=()=>localStorage.setItem(key,JSON.stringify(schedule));const timeNow=()=>new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'});
function active(e,d=new Date()){if(!e.enabled)return false;const day=['sun','mon','tue','wed','thu','fri','sat'][d.getDay()];if(!e.days.includes('daily')&&!e.days.includes(day))return false;const iso=d.toISOString().slice(0,10);return(!e.start_date||iso>=e.start_date)&&(!e.end_date||iso<=e.end_date)}
function renderToday(){const d=new Date();$('#todayDate').textContent=d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'});const now=timeNow();const items=schedule.events.filter(e=>active(e,d)).sort((a,b)=>a.time.localeCompare(b.time));$('#todayList').innerHTML=items.length?items.map(e=>{const due=e.time<=now;return `<article class="reminder-card ${due?'is-due':''}"><div class="reminder-time">${esc(e.time)}</div><div><div class="card-title">${esc(e.label)}</div><div class="card-detail">${esc(e.medicines.join(' · '))}</div></div><span class="status-badge">${due?'Due':'Upcoming'}</span></article>`}).join(''):'<div class="empty">No active reminders today.</div>'}
function renderSchedules(){const list=[...schedule.events].sort((a,b)=>a.time.localeCompare(b.time));$('#scheduleList').innerHTML=list.length?list.map(e=>`<article class="schedule-card"><div class="schedule-top"><div><div class="schedule-time">${esc(e.time)}</div><div class="card-title">${esc(e.label)}</div><div class="card-detail">${e.enabled?'Enabled':'Disabled'} · ${esc(e.days.join(', '))}</div></div><div class="schedule-actions"><button class="small-button" data-edit="${esc(e.id)}">Edit</button><button class="small-button danger" data-remove="${esc(e.id)}">Remove</button></div></div><div class="medicine-chips">${e.medicines.map(m=>`<span class="chip">${esc(m)}</span>`).join('')}</div></article>`).join(''):'<div class="empty">No schedules yet. Add your first reminder.</div>'}
function openEditor(id=null){const e=id?schedule.events.find(x=>x.id===id):{id:'',enabled:true,time:'08:00',label:'',medicines:[''],instructions:'',days:['daily'],start_date:'',end_date:''};$('#dialogTitle').textContent=id?'Edit schedule':'Add schedule';$('#eventId').value=e.id;$('#eventTime').value=e.time;$('#eventLabel').value=e.label;$('#eventInstructions').value=e.instructions||'';$('#eventDays').value=e.days.join(',');$('#eventStart').value=e.start_date||'';$('#eventEnd').value=e.end_date||'';$('#eventEnabled').checked=e.enabled;renderMedicineInputs(e.medicines);$('#scheduleDialog').showModal()}
function renderMedicineInputs(items){$('#medicineList').innerHTML='';items.forEach(addMedicineInput)}function addMedicineInput(value=''){const row=document.createElement('div');row.className='medicine-row';row.innerHTML=`<input required maxlength="500" value="${esc(value)}" placeholder="Medication or item"><button type="button" class="small-button danger" aria-label="Remove medication">×</button>`;row.querySelector('button').onclick=()=>row.remove();$('#medicineList').append(row)}
function saveEditor(){const id=$('#eventId').value||`reminder_${Date.now()}`;const medicines=[...$('#medicineList input')].map(x=>x.value.trim()).filter(Boolean);if(!medicines.length){alert('Add at least one medication or item.');return}const e={id,enabled:$('#eventEnabled').checked,time:$('#eventTime').value,label:$('#eventLabel').value.trim(),medicines,instructions:$('#eventInstructions').value.trim(),days:$('#eventDays').value.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean),start_date:$('#eventStart').value||null,end_date:$('#eventEnd').value||null};if(!e.time||!e.label||!e.days.length){alert('Time, label, and days are required.');return}const index=schedule.events.findIndex(x=>x.id===id);if(index>=0)schedule.events[index]=e;else schedule.events.push(e);save();$('#scheduleDialog').close();renderAll()}
function playSound(){const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext){alert('Sound preview is not supported by this browser.');return}const ctx=new AudioContext(),gainScale=(settings.volume/100)*.16,patterns={chime:[[523,.0,.28],[659,.18,.34],[784,.36,.48]],bright:[[784,.0,.18],[988,.16,.18],[1175,.32,.34]],warm:[[330,.0,.24],[392,.2,.24],[494,.4,.42]],urgent:[[880,.0,.16],[440,.2,.16],[880,.42,.24]],quiet:[[660,.0,.28]]},notes=patterns[settings.sound]||patterns.chime;notes.forEach(([frequency,start,duration])=>{const o=ctx.createOscillator(),g=ctx.createGain(),when=ctx.currentTime+start;o.type=settings.sound==='warm'?'triangle':'sine';o.frequency.value=frequency;g.gain.setValueAtTime(0,when);g.gain.linearRampToValueAtTime(gainScale,when+.025);g.gain.exponentialRampToValueAtTime(.001,when+duration);o.connect(g);g.connect(ctx.destination);o.start(when);o.stop(when+duration+.03)});setTimeout(()=>ctx.close(),900)}
function renderAll(){renderToday();renderSchedules();$('#timezoneInput').value=schedule.timezone;$('#volumeInput').value=settings.volume;$('#volumeOutput').value=`${settings.volume}%`;$('#soundInput').value=settings.sound}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.view}View`).classList.add('active')});$('#addSchedule').onclick=()=>openEditor();$('#addMedicine').onclick=()=>addMedicineInput();$('#saveSchedule').onclick=e=>{e.preventDefault();saveEditor()};$('#volumeInput').oninput=e=>$('#volumeOutput').value=`${e.target.value}%`;$('#testSound').onclick=()=>{settings={...settings,volume:Number($('#volumeInput').value),sound:$('#soundInput').value};playSound()};$('#saveSettings').onclick=()=>{settings={volume:Number($('#volumeInput').value),sound:$('#soundInput').value};schedule.timezone=$('#timezoneInput').value.trim()||'Europe/London';localStorage.setItem(settingsKey,JSON.stringify(settings));save();alert('Settings saved on this device.')};$('#scheduleList').onclick=e=>{const edit=e.target.closest('[data-edit]'),remove=e.target.closest('[data-remove]');if(edit)openEditor(edit.dataset.edit);if(remove&&confirm('Remove this schedule?')){schedule.events=schedule.events.filter(x=>x.id!==remove.dataset.remove);save();renderAll()}};$('#installButton').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installButton').hidden=false});if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');renderAll();setInterval(renderToday,30000);
function updateNotificationStatus(){const status=$('#notificationStatus');const button=$('#enableNotifications');if(!('Notification'in window)){status.textContent='Not supported by this browser';button.disabled=true;return}status.textContent=Notification.permission==='granted'?'Enabled for this device':Notification.permission==='denied'?'Blocked in browser settings':'Not enabled';button.textContent=Notification.permission==='granted'?'Notifications enabled':'Enable notifications'}
async function enableNotifications(){if(!('Notification'in window)){return}const permission=await Notification.requestPermission();updateNotificationStatus();if(permission==='granted')new Notification('Medication Reminder',{body:'Local browser notifications are enabled on this device.'})}
let notifiedKeys=new Set(JSON.parse(localStorage.getItem('medication-reminder-notified-v1')||'[]'));
function checkForegroundNotifications(){if(!('Notification'in window)||Notification.permission!=='granted')return;const now=new Date(),today=now.toISOString().slice(0,10),current=now.toTimeString().slice(0,5);schedule.events.filter(e=>e.enabled&&active(e,now)&&e.time===current).forEach(e=>{const key=`${today}|${e.id}|${e.time}`;if(notifiedKeys.has(key))return;notifiedKeys.add(key);localStorage.setItem('medication-reminder-notified-v1',JSON.stringify([...notifiedKeys].slice(-100)));new Notification(`Medication due: ${e.label}`,{body:e.medicines.join(' · '),tag:key})})}
$('#enableNotifications').onclick=enableNotifications;updateNotificationStatus();setInterval(checkForegroundNotifications,30000);
const pushApi='https://medication-reminder-push.bmorris0565.workers.dev';
function nextPushReminders(){const out=[],now=new Date();for(let day=0;day<8;day++){const d=new Date(now);d.setHours(12,0,0,0);d.setDate(d.getDate()+day);schedule.events.filter(e=>active(e,d)).forEach(e=>{const due=new Date(`${d.toISOString().slice(0,10)}T${e.time}:00`);if(due>now)out.push({dueAt:due.getTime(),title:`Medication due: ${e.label}`,body:e.medicines.join(' · '),tag:`${due.toISOString().slice(0,10)}|${e.id}`})})}return out.sort((a,b)=>a.dueAt-b.dueAt).slice(0,32)}
async function syncPushSubscription(){if(!('serviceWorker'in navigator)||!('PushManager'in window)||Notification.permission!=='granted')return;try{const registration=await navigator.serviceWorker.ready;const publicKey=(await (await fetch(`${pushApi}/vapid-public-key`)).json()).publicKey;let subscription=await registration.pushManager.getSubscription();if(!subscription){const base64=publicKey.replace(/-/g,'+').replace(/_/g,'/');subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:Uint8Array.from(atob(base64+'='.repeat((4-base64.length%4)%4)),c=>c.charCodeAt(0))})}const json=subscription.toJSON();await fetch(`${pushApi}/subscriptions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...json,timezone:schedule.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone,reminders:nextPushReminders()})})}catch(error){console.warn('Push setup unavailable',error)}}
const priorNotificationHandler=$('#enableNotifications').onclick;$('#enableNotifications').onclick=async()=>{await priorNotificationHandler();if(Notification.permission==='granted')await syncPushSubscription()};if(Notification.permission==='granted')syncPushSubscription();
const takenKey='medication-reminder-taken-v1';let taken=JSON.parse(localStorage.getItem(takenKey)||'{}');
function reminderState(e,now){const day=now.toISOString().slice(0,10),key=`${day}|${e.id}`;if(taken[key])return 'Taken';const current=now.toTimeString().slice(0,5);return e.time===current?'Due':e.time<current?'Missed':'Upcoming'}
function renderToday(){const d=new Date();$('#todayDate').textContent=d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'});const items=schedule.events.filter(e=>active(e,d)).sort((a,b)=>a.time.localeCompare(b.time));$('#todayList').innerHTML=items.length?items.map(e=>{const state=reminderState(e,d),day=d.toISOString().slice(0,10),key=`${day}|${e.id}`;return `<article class="reminder-card ${state==='Due'?'is-due':''}"><div class="reminder-time">${esc(e.time)}</div><div><div class="card-title">${esc(e.label)}</div><div class="card-detail">${esc(e.medicines.join(' · '))}</div></div><span class="status-badge">${state}</span>${state!=='Taken'?`<button class="small-button" data-taken="${esc(key)}">Mark taken</button>`:''}</article>`}).join(''):'<div class="empty">No active reminders today.</div>'}
$('#todayList').addEventListener('click',event=>{const button=event.target.closest('[data-taken]');if(!button)return;taken[button.dataset.taken]=Date.now();const entries=Object.entries(taken).filter(([key])=>key>=new Date().toISOString().slice(0,10));taken=Object.fromEntries(entries.slice(-200));localStorage.setItem(takenKey,JSON.stringify(taken));renderToday()});renderToday();
const priorSaveSettings=$('#saveSettings').onclick;$('#saveSettings').onclick=async()=>{await priorSaveSettings();await syncPushSubscription()};
const priorSaveSchedule=$('#saveSchedule').onclick;$('#saveSchedule').onclick=async event=>{await priorSaveSchedule(event);await syncPushSubscription()};
const bridge=document.createElement('div');bridge.className='setting-actions';bridge.innerHTML='<button class="secondary-button" id="exportSchedule">Copy pairing code</button>';$('#settingsView .settings-card').append(bridge);
const qrDialog=document.createElement('dialog');qrDialog.innerHTML='<form method="dialog" class="dialog-card"><h2>Schedule pairing QR</h2><canvas id="pairingQr"></canvas><video id="qrCamera" autoplay playsinline hidden></video><p id="qrStatus" class="privacy-note">Scan this code from another device, or use the camera scanner.</p><div class="dialog-actions"><button type="button" class="secondary-button" id="scanQr">Scan QR</button><button class="primary-button">Close</button></div></form>';document.body.append(qrDialog);bridge.insertAdjacentHTML('beforeend','<button class="secondary-button" id="showQr">Show QR code</button>');
function pairingPayload(){return btoa(unescape(encodeURIComponent(JSON.stringify({version:1,schedule,createdAt:Date.now()}))))}
function decodePairingPayload(raw){const normalized=raw.trim().replace(/-/g,'+').replace(/_/g,'/');return JSON.parse(decodeURIComponent(escape(atob(normalized+'='.repeat((4-normalized.length%4)%4)))))}
function renderPairingQr(code){if(typeof qrcode!=='function')throw Error('QR generator unavailable');const qr=qrcode(0,'L');qr.addData(code);qr.make();const canvas=$('#pairingQr'),ctx=canvas.getContext('2d'),count=qr.getModuleCount(),size=360,cell=size/count;canvas.width=size;canvas.height=size;ctx.fillStyle='#fff';ctx.fillRect(0,0,size,size);ctx.fillStyle='#243044';for(let row=0;row<count;row++)for(let col=0;col<count;col++)if(qr.isDark(row,col))ctx.fillRect(Math.floor(col*cell),Math.floor(row*cell),Math.ceil(cell),Math.ceil(cell))}
$('#showQr').onclick=()=>{try{renderPairingQr(pairingPayload());qrDialog.showModal()}catch{alert('Could not create the QR code. Reload the app and try again.')}};
$('#scanQr').onclick=async()=>{if(!('BarcodeDetector'in window)){alert('QR camera scanning is not supported by this browser. Use Import pairing code instead.');return}try{const video=$('#qrCamera');video.hidden=false;const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});video.srcObject=stream;const detector=new BarcodeDetector({formats:['qr_code']});const scan=async()=>{const codes=await detector.detect(video);if(codes[0]?.rawValue){stream.getTracks().forEach(track=>track.stop());video.hidden=true;try{const data=decodePairingPayload(codes[0].rawValue);if(data.version!==1||!data.schedule?.events)throw Error();schedule=data.schedule;save();renderAll();syncPushSubscription();qrDialog.close();alert('Schedule imported successfully.')}catch{alert('Invalid medication schedule QR code.')}}else requestAnimationFrame(scan)};scan()}catch{alert('Camera access was not granted.')}};
const pairFromUrl=new URLSearchParams(location.search).get('pair');if(pairFromUrl){try{renderPairingQr(pairFromUrl);qrDialog.showModal()}catch{alert('Could not display the widget pairing QR code.')}}
$('#exportSchedule').onclick=async()=>{const payload=btoa(unescape(encodeURIComponent(JSON.stringify({version:1,schedule,createdAt:Date.now()}))));await navigator.clipboard?.writeText(payload);prompt('Pairing code (copy this to the other device):',payload)};
$('#importSchedule').onclick=()=>{const raw=prompt('Paste the pairing code from the other device:');if(!raw)return;try{const data=decodePairingPayload(raw);if(data.version!==1||!data.schedule?.events)throw Error('Invalid pairing code');schedule=data.schedule;save();renderAll();syncPushSubscription();alert('Schedule imported on this device.')}catch{alert('That pairing code is invalid or incomplete.')}};
if('serviceWorker'in navigator){navigator.serviceWorker.ready.then(registration=>{registration.update();setInterval(()=>registration.update(),15*60*1000)})}
