(() => {
  'use strict';
  const API='https://medication-reminder-push.bmorris0565.workers.dev',APP_URL='https://medication.bytesfx.com/';
  const CREDENTIALS_KEY='medication-reminder-sync-v1',SOURCE_ID_KEY='medication-reminder-source-id-v1',MOBILE_ID_KEY='medication-reminder-mobile-id-v1';
  const status=document.querySelector('#syncStatus'),pairButton=document.querySelector('#showQr'),copyButton=document.querySelector('#exportSchedule'),syncButton=document.querySelector('#importSchedule'),unpairButton=document.querySelector('#unpairDevice');
  const installedStandalone=matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true;
  const mobileDevice=Boolean(navigator.userAgentData?.mobile)||/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);
  const installedMobile=installedStandalone&&mobileDevice;
  let pushTimer=0,syncInProgress=false,changeGeneration=0;
  function b64(bytes){let binary='';for(const value of bytes)binary+=String.fromCharCode(value);return btoa(binary).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/g,'')}
  function unb64(value){const normalized=value.replace(/-/g,'+').replace(/_/g,'/'),binary=atob(normalized+'='.repeat((4-normalized.length%4)%4));return Uint8Array.from(binary,character=>character.charCodeAt(0))}
  const randomId=(length=24)=>b64(crypto.getRandomValues(new Uint8Array(length)));
  function storedJson(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}
  function credentials(){const value=storedJson(CREDENTIALS_KEY);return value&&value.version===1?value:null}
  function saveCredentials(value){localStorage.setItem(CREDENTIALS_KEY,JSON.stringify(value));refreshStatus(value)}
  function stableId(key){let value=localStorage.getItem(key);if(!value){value=randomId();localStorage.setItem(key,value)}return value}
  function refreshControls(value=credentials()){if(installedMobile){pairButton.hidden=true;copyButton.hidden=true;const paired=value?.role==='mobile';syncButton.hidden=!paired;unpairButton.hidden=false;unpairButton.textContent=paired?'Unpair':'Pair Schedule';return}pairButton.hidden=false;copyButton.hidden=false;syncButton.hidden=false;unpairButton.hidden=!value;unpairButton.textContent='Unpair'}
  function refreshStatus(value=credentials(),message=''){if(status){status.classList.remove('is-error');status.textContent=message||(!value?(installedMobile?'No schedule is paired with this mobile app.':'Schedules are stored privately on this device.'):value.role==='mobile'?`Paired mobile · revision ${value.revision} · encrypted sync ready`:`Mobile pairing ready · revision ${value.revision}${value.claimed?' · mobile connected':' · waiting for mobile scan'}`)}refreshControls(value)}
  function showError(message){if(status){status.textContent=message;status.classList.add('is-error')}}
  function validateSchedule(value){
    if(!value||typeof value!=='object'||typeof value.timezone!=='string'||value.timezone.length>100||!Array.isArray(value.events)||value.events.length>64)throw Error('The encrypted schedule is invalid.');
    const events=value.events.map(item=>{if(!item||typeof item!=='object'||typeof item.id!=='string'||!/^[A-Za-z0-9_-]{1,128}$/.test(item.id)||typeof item.time!=='string'||!/^([01]\d|2[0-3]):[0-5]\d$/.test(item.time)||typeof item.label!=='string'||!item.label.trim()||item.label.length>200||!Array.isArray(item.medicines)||!item.medicines.length||item.medicines.length>32||!Array.isArray(item.days)||!item.days.length)throw Error('The encrypted schedule contains an invalid reminder.');if(item.medicines.some(medicine=>typeof medicine!=='string'||!medicine.trim()||medicine.length>500))throw Error('The encrypted schedule contains an invalid medication.');const days=item.days.map(day=>String(day).toLowerCase()).filter(day=>/^(daily|mon|tue|wed|thu|fri|sat|sun)$/.test(day));if(!days.length)throw Error('The encrypted schedule contains invalid active days.');return{id:item.id,enabled:Boolean(item.enabled),time:item.time,label:item.label.trim(),medicines:item.medicines.map(medicine=>medicine.trim()),instructions:typeof item.instructions==='string'?item.instructions.slice(0,2000):'',days,start_date:typeof item.start_date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(item.start_date)?item.start_date:null,end_date:typeof item.end_date==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(item.end_date)?item.end_date:null}});
    return{version:1,timezone:value.timezone,events};
  }
  const importKey=encoded=>crypto.subtle.importKey('raw',unb64(encoded),{name:'AES-GCM'},false,['encrypt','decrypt']);
  async function encryptSchedule(schedule,key){const iv=crypto.getRandomValues(new Uint8Array(12)),plain=new TextEncoder().encode(JSON.stringify(validateSchedule(schedule))),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},await importKey(key),plain);return{iv:b64(iv),ciphertext:b64(new Uint8Array(cipher))}}
  async function decryptSchedule(remote,key){try{const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(remote.iv)},await importKey(key),unb64(remote.ciphertext));return validateSchedule(JSON.parse(new TextDecoder().decode(plain)))}catch(error){console.error('Encrypted schedule validation failed',error);throw Error('This pairing link cannot decrypt the schedule. It may be damaged or expired.')}}
  async function api(path,options={}){const response=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})},cache:'no-store'});let body={};try{body=await response.json()}catch{}if(!response.ok){const error=Error(body.error||`Sync request failed (${response.status}).`);error.status=response.status;error.body=body;throw error}return body}
  const auth=value=>({Authorization:`Bearer ${value.token}`});
  function pairingLink(value){const payload=b64(new TextEncoder().encode(JSON.stringify({version:1,pairId:value.pairId,token:value.token,encryptionKey:value.encryptionKey})));return`${APP_URL}#pair=${payload}`}
  function parseInvitation(raw=location.href){let hash='';try{hash=raw.startsWith('#')?raw:new URL(raw,location.href).hash}catch{throw Error('The QR pairing link is invalid or incomplete.')}if(!hash.startsWith('#pair='))return null;try{const value=JSON.parse(new TextDecoder().decode(unb64(hash.slice(6))));if(value.version!==1||!/^[A-Za-z0-9_-]{16,128}$/.test(value.pairId||'')||typeof value.token!=='string'||value.token.length<32||typeof value.encryptionKey!=='string'||unb64(value.encryptionKey).length!==32)throw Error();return value}catch{throw Error('The QR pairing link is invalid or incomplete.')}}
  const dialog=document.createElement('dialog');dialog.innerHTML='<form method="dialog" class="dialog-card"><div class="dialog-heading"><div><p class="eyebrow">PRIVATE DEVICE LINK</p><h2>Pair one mobile device</h2></div><button class="close-button" aria-label="Close">×</button></div><canvas id="securePairingQr" class="pairing-code"></canvas><p class="pairing-note">Scan with the mobile camera. The link opens or installs this app, then asks before pairing. The encryption key stays inside the QR link.</p><div class="dialog-actions"><button type="button" id="copySecurePairLink" class="secondary-button">Copy link</button><button class="primary-button">Done</button></div></form>';document.body.append(dialog);
  const scannerDialog=document.createElement('dialog');scannerDialog.innerHTML='<form method="dialog" class="dialog-card"><div class="dialog-heading"><div><p class="eyebrow">PAIR SCHEDULE</p><h2>Scan pairing QR</h2></div><button class="close-button" aria-label="Close">×</button></div><video id="secureQrCamera" class="qr-reader-video" autoplay playsinline muted></video><p id="secureQrStatus" class="pairing-note">Point the camera at the QR code displayed by the browser or Windows widget.</p><div class="dialog-actions"><button type="button" id="pasteSecurePairLink" class="secondary-button">Paste link</button><button class="primary-button">Cancel</button></div></form>';document.body.append(scannerDialog);
  let scannerStream=null,scannerFrame=0,scannerBusy=false;
  function stopScanner(){if(scannerFrame)cancelAnimationFrame(scannerFrame);scannerFrame=0;scannerBusy=false;if(scannerStream){scannerStream.getTracks().forEach(track=>track.stop());scannerStream=null}const video=scannerDialog.querySelector('#secureQrCamera');video.srcObject=null}
  async function useScannedPairing(raw){let invitation;try{invitation=parseInvitation(raw)}catch(error){scannerDialog.querySelector('#secureQrStatus').textContent=error.message;return false}if(!invitation){scannerDialog.querySelector('#secureQrStatus').textContent='This is not a Medication Reminder pairing QR code.';return false}stopScanner();scannerDialog.close();try{await acceptPairing(invitation)}catch(error){showError(error.message);alert(`Pairing failed: ${error.message}`)}return true}
  async function openScanner(){if(!installedMobile){alert('QR scanning is available from the installed mobile app.');return}if(!('BarcodeDetector'in window)){const raw=prompt('This device does not provide an in-app QR detector. Paste the private pairing link instead:');if(raw)await useScannedPairing(raw);return}const statusText=scannerDialog.querySelector('#secureQrStatus');statusText.textContent='Starting camera…';scannerDialog.showModal();try{scannerStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}}});const video=scannerDialog.querySelector('#secureQrCamera');video.srcObject=scannerStream;await video.play();const detector=new BarcodeDetector({formats:['qr_code']});statusText.textContent='Point the camera at the QR code displayed by the browser or Windows widget.';const scan=async()=>{if(!scannerStream||scannerBusy)return;scannerBusy=true;try{if(video.readyState>=2){const codes=await detector.detect(video);if(codes[0]?.rawValue&&await useScannedPairing(codes[0].rawValue))return}}catch(error){statusText.textContent=`QR scan failed: ${error.message}`}finally{scannerBusy=false}if(scannerStream)scannerFrame=requestAnimationFrame(scan)};scannerFrame=requestAnimationFrame(scan)}catch(error){stopScanner();scannerDialog.close();alert('Camera access is required to scan the pairing QR code. You can allow camera access in the app or browser settings.')}}
  scannerDialog.addEventListener('close',stopScanner);
  scannerDialog.querySelector('#pasteSecurePairLink').onclick=async()=>{const raw=prompt('Paste the private pairing link:');if(raw)await useScannedPairing(raw)};
  function drawQr(text){if(typeof qrcode!=='function')throw Error('QR generator unavailable.');const qr=qrcode(0,'M');qr.addData(text);qr.make();const canvas=dialog.querySelector('#securePairingQr'),context=canvas.getContext('2d'),count=qr.getModuleCount(),size=360,cell=size/count;canvas.width=size;canvas.height=size;context.fillStyle='#fff';context.fillRect(0,0,size,size);context.fillStyle='#243044';for(let row=0;row<count;row++)for(let column=0;column<count;column++)if(qr.isDark(row,column))context.fillRect(Math.floor(column*cell),Math.floor(row*cell),Math.ceil(cell),Math.ceil(cell))}
  async function createPair(){const current=credentials();if(current&&!confirm('Create a new pairing? The existing mobile link will stop syncing.'))return current;refreshStatus(null,'Creating encrypted pairing…');const sourceId=stableId(SOURCE_ID_KEY),value={version:1,role:'source',pairId:randomId(),token:randomId(32),encryptionKey:randomId(32),deviceId:sourceId,sourceId,revision:1,claimed:false,dirty:false},encrypted=await encryptSchedule(window.getMedicationSchedule(),value.encryptionKey);await api('/sync/pairs',{method:'POST',body:JSON.stringify({pairId:value.pairId,sourceId:value.sourceId,token:value.token,updatedBy:value.deviceId,...encrypted})});saveCredentials(value);return value}
  async function showPairing(){try{let value=credentials();if(!value||value.role!=='source')value=await createPair();drawQr(pairingLink(value));dialog.showModal()}catch(error){showError(error.message);alert(`Could not create pairing: ${error.message}`)}}
  async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{prompt('Copy this private pairing link:',text);return false}}
  async function copyPairLink(){try{let value=credentials();if(!value||value.role!=='source')value=await createPair();if(await copyText(pairingLink(value)))refreshStatus(value,'Private pairing link copied.')}catch(error){showError(error.message);alert(`Could not copy pairing link: ${error.message}`)}}
  async function acceptPairing(invitation){if(!confirm('Pair this mobile device and replace its local schedule with the encrypted schedule from the source device?')){history.replaceState(null,'',`${location.pathname}${location.search}`);return}const current=credentials();if(current&&current.pairId!==invitation.pairId){try{await api(`/sync/pairs/${encodeURIComponent(current.pairId)}`,{method:'DELETE',headers:auth(current)})}catch(error){if(error.status!==404)throw Error(`The existing pairing could not be replaced: ${error.message}`)}}const mobileId=stableId(MOBILE_ID_KEY);refreshStatus(null,'Securely pairing this mobile…');let pushEndpoint=null;try{if('Notification'in window&&Notification.permission==='default'&&confirm('Enable medication and schedule-update notifications on this mobile device?')){const setup=document.querySelector('#enableNotifications')?.onclick?.();await Promise.race([setup,new Promise(resolve=>setTimeout(resolve,8000))])}pushEndpoint=await Promise.race([window.getMedicationPushEndpoint(),new Promise(resolve=>setTimeout(()=>resolve(null),8000))])}catch(error){console.warn('Notification setup skipped; pairing will continue',error);pushEndpoint=null}await api(`/sync/pairs/${encodeURIComponent(invitation.pairId)}/claim`,{method:'POST',headers:{Authorization:`Bearer ${invitation.token}`},body:JSON.stringify({mobileDeviceId:mobileId,pushEndpoint})});const remote=await api(`/sync/pairs/${encodeURIComponent(invitation.pairId)}`,{headers:{Authorization:`Bearer ${invitation.token}`}}),imported=await decryptSchedule(remote,invitation.encryptionKey);window.applySyncedSchedule(imported);saveCredentials({...invitation,role:'mobile',deviceId:mobileId,revision:remote.revision,claimed:true,dirty:false});history.replaceState(null,'',`${location.pathname}${location.search}`);alert('This mobile device is now paired. Schedule changes sync securely while the app is open.')}
  async function syncNow({pushLocal=false,silent=false}={}){const value=credentials();if(!value||syncInProgress){if(!value&&!silent)alert('Pair a mobile device first.');return}const generation=changeGeneration;syncInProgress=true;refreshStatus(value,'Syncing encrypted schedule…');try{const remote=await api(`/sync/pairs/${encodeURIComponent(value.pairId)}`,{headers:auth(value)});value.claimed=remote.claimed;if(changeGeneration!==generation)value.dirty=true;const remoteChanged=remote.revision!==value.revision&&remote.updatedBy!==value.deviceId;if(remoteChanged&&value.dirty){const overwrite=confirm('Schedule changes were made on both devices.\n\nOK: keep this device’s version and overwrite the other device.\nCancel: use the other device’s version here.');if(!overwrite){window.applySyncedSchedule(await decryptSchedule(remote,value.encryptionKey));value.revision=remote.revision;value.dirty=false;saveCredentials(value);return}value.revision=remote.revision}else if(remoteChanged||(!value.dirty&&remote.revision>value.revision)){window.applySyncedSchedule(await decryptSchedule(remote,value.encryptionKey));value.revision=remote.revision;value.dirty=false;saveCredentials(value);return}if(value.dirty||pushLocal){const encrypted=await encryptSchedule(window.getMedicationSchedule(),value.encryptionKey),updated=await api(`/sync/pairs/${encodeURIComponent(value.pairId)}`,{method:'PUT',headers:auth(value),body:JSON.stringify({baseRevision:remote.revision,updatedBy:value.deviceId,...encrypted})});value.revision=updated.revision;value.dirty=changeGeneration!==generation}else value.revision=remote.revision;saveCredentials(value)}catch(error){if(error.status===404){localStorage.removeItem(CREDENTIALS_KEY);if(value.role==='mobile')window.clearMedicationSchedule();refreshStatus(null,value.role==='mobile'?'Pairing ended. Local schedules were removed.':'Pairing ended. Create a new mobile pairing when ready.');if(!silent)alert('This pairing has ended. Pair the devices again to resume sync.');return}showError(`Sync failed: ${error.message}`);if(!silent)alert(`Sync failed: ${error.message}`)}finally{syncInProgress=false;if(credentials()?.dirty){clearTimeout(pushTimer);pushTimer=setTimeout(()=>void syncNow({pushLocal:true,silent:true}),1000)}}}
  async function unpair(){const value=credentials();if(!value){if(installedMobile)await openScanner();return}if(installedMobile&&value.role!=='mobile'){if(!confirm('Replace this app’s old pairing and scan a schedule source now?'))return;try{await api(`/sync/pairs/${encodeURIComponent(value.pairId)}`,{method:'DELETE',headers:auth(value)})}catch(error){if(error.status!==404){alert(`Could not replace the old pairing: ${error.message}`);return}}localStorage.removeItem(CREDENTIALS_KEY);window.clearMedicationSchedule();refreshStatus(null,'Old pairing removed. Scan the browser or widget QR code.');await openScanner();return}const eraseMobile=value.role==='mobile'||installedMobile;if(eraseMobile){const verification=prompt('Unpairing will permanently remove all schedules and taken-state data from this mobile app.\n\nType UNPAIR to continue:');if(verification!=='UNPAIR')return}else if(!confirm('Unpair this device? This revokes the shared encrypted schedule and stops sync on both devices.'))return;try{await api(`/sync/pairs/${encodeURIComponent(value.pairId)}`,{method:'DELETE',headers:auth(value)})}catch(error){if(error.status!==404){alert(`Could not revoke pairing: ${error.message}`);return}}localStorage.removeItem(CREDENTIALS_KEY);if(eraseMobile)window.clearMedicationSchedule();refreshStatus(null,eraseMobile?'Unpaired. All schedules were removed from this mobile app.':'Device unpaired. Your local schedule was kept.')}
  window.addEventListener('medication-schedule-changed',()=>{const value=credentials();if(!value)return;changeGeneration+=1;value.dirty=true;saveCredentials(value);clearTimeout(pushTimer);pushTimer=setTimeout(()=>void syncNow({pushLocal:true,silent:true}),700)});
  pairButton.onclick=showPairing;copyButton.onclick=copyPairLink;syncButton.onclick=()=>void syncNow();unpairButton.onclick=unpair;dialog.querySelector('#copySecurePairLink').onclick=()=>{const value=credentials();if(value)void copyText(pairingLink(value))};
  refreshStatus();document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')void syncNow({silent:true})});window.addEventListener('focus',()=>void syncNow({silent:true}));setInterval(()=>{if(document.visibilityState==='visible')void syncNow({silent:true})},60000);
  try{const invitation=parseInvitation();if(invitation)void acceptPairing(invitation).catch(error=>{history.replaceState(null,'',`${location.pathname}${location.search}`);showError(error.message);alert(`Pairing failed: ${error.message}`)});else if(credentials())void syncNow({silent:true})}catch(error){history.replaceState(null,'',`${location.pathname}${location.search}`);showError(error.message);alert(error.message)}
  window.MedicationSync={createPair,syncNow,unpair};
})();
